spring:
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3307/clothingstoremanager}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:root}
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update